export const SQS_DEFAULT_MESSAGE_VISIBILITY_TIMEOUT = 60;
export const SQS_DEFAULT_MAX_NUMBER_OF_MESSAGES = 10;
export const SQS_DEFAULT_AUTO_DELETE_MESSAGE = true;
export const SQS_DEFAULT_WAIT_TIME_SECONDS = 20;
